# fly.toml app configuration file generated for weather-whatsapp-bot on 2025-08-08T00:43:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weather-whatsapp-bot"
primary_region = "arn"

[build]

[mounts]
  source = "data"
  destination = "/data"

[processes]
  web = "gunicorn app:app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  # auto_stop_machines = true
  min_machines_running = 1
  processes = ["web"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
