name: Weather Bot Scheduler

on:
  schedule:
    - cron: '30 6 * * *'   # 08:30 Sweden time
    - cron: '16 16 * * *'  # 18:00 Sweden time

jobs:
  send-today:
    if: github.event.schedule == '30 6 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v0.0.2
      - name: Start machine for today's weather
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl machines start ${{ secrets.FLY_MACHINE_ID }} -a ${{ secrets.FLY_APP_NAME }} \
          -d '{"entrypoint":["python","weather_bot.py"]}'

  send-tomorrow:
    if: github.event.schedule == '16 16 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v0.0.2
      - name: Start machine for tomorrow's weather
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl machines start ${{ secrets.FLY_MACHINE_ID }} -a ${{ secrets.FLY_APP_NAME }} \
          -d '{"entrypoint":["python","weather_bot.py","--tomorrow"]}'
