name: Stop Fly Machine

on:
  workflow_run:
    workflows:
      - Weather Bot Every 5 min
      - Weather Bot Today's Forecast
      - Weather Bot Tomorrow's Forecast
      - Weather Bot Manual Dispatch
    types:
      - completed

jobs:
  stop_fly_machine:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Fly.io machine
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_API_HOSTNAME: "https://api.machines.fly.io"
          APP_NAME: "weather-whatsapp-bot"
          MACHINE_ID: ${{ secrets.MACHINE_ID }}
        run: |
          curl -i -X POST \
            -H "Authorization: Bearer $FLY_API_TOKEN" \
            -H "Content-Type: application/json" \
            "$FLY_API_HOSTNAME/v1/apps/$APP_NAME/machines/$MACHINE_ID/stop"
