name: Weather Bot Every 5 min

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  send-forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Start machine
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          TOMORROW: "true"  # today or tomorrow
        run: |
          flyctl machine start ${{ secrets.MACHINE_ID }} \
          -a ${{ secrets.FLY_APP_NAME }}
