name: Weather Bot Every 5 min

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/1 * * * *'

jobs:
  send-forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Start machine
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl secrets set TOMORROW=true -a "${{ secrets.FLY_APP_NAME }}"
          flyctl machine start ${{ secrets.MACHINE_ID }} \
          -a ${{ secrets.FLY_APP_NAME }}
